import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import loreBook from '../assets/loreBook.png'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'

const lore = () => {
  return (
    <div>
      <Head>
        <title>Shredding Sassy | Lore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
        <Image
          src={loreBook}
          alt='Lore Book'
          width={1560}
          height={650}
        >
        </Image>
      <Footer />
    </div>
  )
}

export default lore