import React from 'react'
import Head from 'next/head'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'

const shop = () => {
  return (
    <div>
      <Head>
        <title>Shredding Sassy | Shop </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='flex flex-col space-y-8 items-center text-center justify-center p-20'>
        <h1 className='text-darkpurple2 font-bold text-4xl'>SHOP</h1>
        <p className='flex items-center text-darkpurple2 text-lg font-medium'>...COMING SOON</p>
      </div>
      <Footer />
    </div>
  )
}

export default shop